# Generated by Django 5.2.8 on 2025-11-14 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, unique=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_state',
            },
        ),
        migrations.CreateModel(
            name='DimActor',
            fields=[
                ('actor_key', models.AutoField(primary_key=True, serialize=False)),
                ('actor_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'dim_actor',
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='dim_actor_last_na_eb8c69_idx'), models.Index(fields=['actor_id'], name='dim_actor_actor_i_2f6c14_idx')],
            },
        ),
        migrations.CreateModel(
            name='DimCategory',
            fields=[
                ('category_key', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=25)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'dim_category',
                'indexes': [models.Index(fields=['name'], name='dim_categor_name_c00d0c_idx'), models.Index(fields=['category_id'], name='dim_categor_categor_f3296b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DimCustomer',
            fields=[
                ('customer_key', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('active', models.BooleanField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'dim_customer',
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='dim_custome_last_na_fd5f5a_idx'), models.Index(fields=['city'], name='dim_custome_city_c0b2f3_idx'), models.Index(fields=['country'], name='dim_custome_country_fec335_idx'), models.Index(fields=['customer_id'], name='dim_custome_custome_b1d371_idx')],
            },
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('date_key', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day_of_month', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('is_weekend', models.BooleanField()),
            ],
            options={
                'db_table': 'dim_date',
                'indexes': [models.Index(fields=['year', 'month'], name='dim_date_year_392d77_idx'), models.Index(fields=['date'], name='dim_date_date_e0af2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DimFilm',
            fields=[
                ('film_key', models.AutoField(primary_key=True, serialize=False)),
                ('film_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'dim_film',
                'indexes': [models.Index(fields=['film_id'], name='dim_film_film_id_c26f36_idx'), models.Index(fields=['title'], name='dim_film_title_2dce63_idx')],
            },
        ),
        migrations.CreateModel(
            name='DimStore',
            fields=[
                ('store_key', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'dim_store',
                'indexes': [models.Index(fields=['city'], name='dim_store_city_bbeed6_idx'), models.Index(fields=['country'], name='dim_store_country_b9b769_idx'), models.Index(fields=['store_id'], name='dim_store_store_i_d5c4e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='BridgeFilmCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncapp.dimcategory')),
                ('film_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncapp.dimfilm')),
            ],
            options={
                'db_table': 'bridge_film_category',
                'indexes': [models.Index(fields=['film_key'], name='bridge_film_film_ke_7ab2bc_idx'), models.Index(fields=['category_key'], name='bridge_film_categor_1af8ac_idx')],
                'unique_together': {('film_key', 'category_key')},
            },
        ),
        migrations.CreateModel(
            name='BridgeFilmActor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncapp.dimactor')),
                ('film_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncapp.dimfilm')),
            ],
            options={
                'db_table': 'bridge_film_actor',
                'indexes': [models.Index(fields=['film_key'], name='bridge_film_film_ke_e08e3d_idx'), models.Index(fields=['actor_key'], name='bridge_film_actor_k_1a5f70_idx')],
                'unique_together': {('film_key', 'actor_key')},
            },
        ),
        migrations.CreateModel(
            name='FactPayment',
            fields=[
                ('fact_payment_key', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.IntegerField(unique=True)),
                ('staff_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncapp.dimcustomer')),
                ('date_key_paid', models.ForeignKey(db_column='date_key_paid', on_delete=django.db.models.deletion.PROTECT, related_name='payments_paid_on', to='syncapp.dimdate')),
                ('store_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncapp.dimstore')),
            ],
            options={
                'db_table': 'fact_payment',
                'indexes': [models.Index(fields=['payment_id'], name='fact_paymen_payment_fe23d0_idx'), models.Index(fields=['date_key_paid'], name='fact_paymen_date_ke_5559e6_idx'), models.Index(fields=['customer_key'], name='fact_paymen_custome_473720_idx'), models.Index(fields=['store_key'], name='fact_paymen_store_k_a90f6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactRental',
            fields=[
                ('fact_rental_key', models.AutoField(primary_key=True, serialize=False)),
                ('rental_id', models.IntegerField(unique=True)),
                ('staff_id', models.IntegerField()),
                ('rental_duration_days', models.IntegerField(blank=True, null=True)),
                ('customer_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncapp.dimcustomer')),
                ('date_key_rented', models.ForeignKey(db_column='date_key_rented', on_delete=django.db.models.deletion.PROTECT, related_name='rentals_rented_on', to='syncapp.dimdate')),
                ('date_key_returned', models.ForeignKey(blank=True, db_column='date_key_returned', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rentals_returned_on', to='syncapp.dimdate')),
                ('film_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncapp.dimfilm')),
                ('store_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncapp.dimstore')),
            ],
            options={
                'db_table': 'fact_rental',
                'indexes': [models.Index(fields=['rental_id'], name='fact_rental_rental__7aa763_idx'), models.Index(fields=['date_key_rented'], name='fact_rental_date_ke_2b4bee_idx'), models.Index(fields=['date_key_returned'], name='fact_rental_date_ke_2c46ba_idx'), models.Index(fields=['film_key'], name='fact_rental_film_ke_0a0b8f_idx'), models.Index(fields=['store_key'], name='fact_rental_store_k_d71866_idx'), models.Index(fields=['customer_key'], name='fact_rental_custome_f96b60_idx')],
            },
        ),
    ]
